config/routes.rb
Rails.application.routes.draw do
  root "photos#index"
  resources :photos
  patch 'croppable/:id', to: 'photos#croppable', as: 'croppable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_one_attached :image
  has_one_attached :cropped_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: %i[ show edit update destroy croppable ]

  def index
    @photos = Photo.all
  end

  def show; end
  def edit; end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    respond_to do |format|
      if @photo.save
        format.html { redirect_to photo_url(@photo) }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to photo_url(@photo) }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url }
    end
  end

  def croppable
    @photo.cropped_image.attach(
      io: StringIO.new(Base64.decode64(photo_params[:cropped_image].split(',')[1])),
      filename: 'cropped_image.jpg',
      content_type: 'image/jpg'
    )
  end

  private

  def set_photo
    @photo = Photo.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(
      :name,
      :image,
      :cropped_image
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand me-5" href="/">Image Cropping</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse ms-5" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= new_photo_path %>">Add Photo</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Image Cropping</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <header>
      <%= render "layouts/nav" %>
    </header>

    <main class="container p-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_with(model: photo) do |form| %>

  <% if photo.errors.any? %>
    <p><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved</p>
    <% photo.errors.each do |error| %>
      <p><%= error.full_message %></p>
    <% end %>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div><br>

  <div class="mt-3">
    <%= form.submit class: "btn btn-sm btn-success" %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<div id="<%= dom_id photo %>">
  <% image_url = photo.image.attached? ? url_for(photo.image) : "" %>
  <% cropped_image_url = photo.cropped_image.attached? ? url_for(photo.cropped_image) : "" %>

  <h4 class="text-muted mb-3">
    <%= photo.name %>
  </h4>

  <%= content_tag(:div, "", data: { controller: "images", images_url: image_url, images_id: photo.id }, class: 'container') do %>
    <div class="image-container">
      <%= image_tag(image_url, class: 'image', id: 'source', data: { images_target: 'source' }) %>
      <div class="mt-3">
        <%= button_to "Crop", '#', data: { action: 'click->images#click', images_target: 'cropButton' }, method: :get, class: "btn btn-sm btn-success px-5" %>
      </div>
    </div>

    <div class="image-container">
      <%= image_tag(cropped_image_url, class: "image", id: "output", data: { images_target: "output" }) %>
    </div>
  <% end %>
</div>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render "form", photo: @photo %>

<br>

<div>
  <%= link_to "Show this photo", @photo %> |
  <%= link_to "Back to photos", photos_path %>
</div>

app/views/photos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-center mb-5">
  Photos
</h1><br>

<% @photos.each do |photo| %>
  <%= render photo %>
  <p>
    <%= link_to "Show photo", photo, class: "float-end text-success" %>
  </p>
<% end %>

<p>
  <%= link_to "New photo", new_photo_path %>
</p>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render "form", photo: @photo %>

<br>

<div>
  <%= link_to "Back to photos", photos_path %>
</div>

app/views/photos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @photo %>

<div>
  <%= link_to "Edit this photo", edit_photo_path(@photo) %> |
  <%= link_to "Back to photos", photos_path %>

  <%= button_to "Destroy this photo", @photo, method: :delete %>
</div>